CREATE TABLE reservation (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_date DATE NOT NULL,
    reservation_start_time TIME NOT NULL,
    reservation_end_time TIME NOT NULL,
    reservation_court_id BIGINT NOT NULL,
    reservation_user_id BIGINT NOT NULL,
    reservation_state VARCHAR(20) NOT NULL,
    CONSTRAINT chk_reservation_state
        CHECK (reservation_state IN ('ACTIVO', 'CANCELADO')),
    CONSTRAINT chk_reservation_time
        CHECK (reservation_end_time > reservation_start_time)
);

CREATE INDEX idx_reservation_date_state
    ON reservation (reservation_date, reservation_state);

CREATE INDEX idx_reservation_user_state_date
    ON reservation (reservation_user_id, reservation_state, reservation_date, reservation_start_time);

CREATE INDEX idx_reservation_court_date_time
    ON reservation (reservation_court_id, reservation_date, reservation_start_time, reservation_end_time);
